
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-sitemap
show_downloads: [true]
github:
  zip_url: https://github.com/spektor56/OpenpilotToolkit/releases/download/1.9.1/OpenpilotToolkit.zip
  tar_url: https://github.com/spektor56/OpenpilotToolkit/releases/download/1.8.1/com.spektor56.openpilottoolkitandroid.apk
